import { eq } from "drizzle-orm";
import { db } from "./db";
import { atletas, eventos, Result, Event } from "./db/schema";
import { randomUUID } from "node:crypto";

// console.log(randomUUID());

// const resultadoSub15MascEtapa01New = [
//     { atleta: "Arthur Silva", categoria: "Sub-15-Masc", posicao: 1, pontos: 1000 },
//     { atleta: "Noah Ribeiro", categoria: "Sub-15-Masc", posicao: 7, pontos: 555 },
//     { atleta: "Matheus Figueiredo", categoria: "Sub-15-Masc", posicao: 3, pontos: 730 },
//     { atleta: "Caio Henrique", categoria: "Sub-15-Masc", posicao: 5, pontos: 610 },
//     { atleta: "Davi Carvalho", categoria: "Sub-15-Masc", posicao: 2, pontos: 860 },
//     { atleta: "Lucas Avellar", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
//     { atleta: "Guilherme Almeida", categoria: "Sub-15-Masc", posicao: 7, pontos: 555 },
//     { atleta: "Arthur Carvalho", categoria: "Sub-15-Masc", posicao: 10, pontos: 488 },
//     { atleta: "Rafael Lorenzo", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
//     { atleta: "Gael Chaves", categoria: "Sub-15-Masc", posicao: 5, pontos: 610 },
//     { atleta: "Nyas Chalfun", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Ryan Suricato", categoria: "Sub-15-Masc", posicao: 10, pontos: 488 },
//     { atleta: "Caua Guedes", categoria: "Sub-15-Masc", posicao: 10, pontos: 488 },
//     { atleta: "Guilherme Henrique", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Leyr Neto", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
//     { atleta: "Yuri Franco", categoria: "Sub-15-Masc", posicao: 4, pontos: 670 },
//     { atleta: "Henrique Gaglionelli", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Luiz Guilherme", categoria: "Sub-15-Masc", posicao: 7, pontos: 555 },
//     { atleta: "Joao Pomato", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Miguel Soares", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Joao Teles", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Nathan De Olveira", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Nathan Silva", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Matheus Ulrick", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Julio Cesar", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Leo Victor", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
//     { atleta: "Joao Victor Lisboa", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
//     { atleta: "Gabriel Ferreira", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
//     { atleta: "Kayllon Miguel", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Julio Cezar", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Marco Antonio", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Nelvan Ferreira", categoria: "Sub-15-Masc", posicao: 19, pontos: 390 },
//     { atleta: "Irineu Correa", categoria: "Sub-15-Masc", posicao: 19, pontos: 390 },
//     { atleta: "Gabriel Aquino", categoria: "Sub-15-Masc", posicao: 19, pontos: 390 },
//     { atleta: "Arthur Leal", categoria: "Sub-15-Masc", posicao: 19, pontos: 390 },
//     { atleta: "Adailton Vieira", categoria: "Sub-15-Masc", posicao: 19, pontos: 390 },
// ];

// const resultadoSub15MascEtapa02New = [
//     { atleta: "Arthur Silva", categoria: "Sub-15-Masc", posicao: 3, pontos: 730 },
//     { atleta: "Noah Ribeiro", categoria: "Sub-15-Masc", posicao: 1, pontos: 1000 },
//     { atleta: "Matheus Figueiredo", categoria: "Sub-15-Masc", posicao: 2, pontos: 860 },
//     { atleta: "Caio Henrique", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
//     { atleta: "Davi Carvalho", categoria: "Sub-15-Masc", posicao: 7, pontos: 555 },
//     { atleta: "Lucas Avellar", categoria: "Sub-15-Masc", posicao: 5, pontos: 610 },
//     { atleta: "Guilherme Almeida", categoria: "Sub-15-Masc", posicao: 4, pontos: 670 },
//     { atleta: "Arthur Carvalho", categoria: "Sub-15-Masc", posicao: 5, pontos: 610 },
//     { atleta: "Rafael Lorenzo", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
//     { atleta: "Gael Chaves", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Nyas Chalfun", categoria: "Sub-15-Masc", posicao: 7, pontos: 555 },
//     { atleta: "Ryan Suricato", categoria: "Sub-15-Masc", posicao: 10, pontos: 488 },
//     { atleta: "Caua Guedes", categoria: "Sub-15-Masc", posicao: 10, pontos: 488 },
//     { atleta: "Guilherme Henrique", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
//     { atleta: "Leyr Neto", categoria: "Sub-15-Masc", posicao: 19, pontos: 390 },
//     { atleta: "Yuri Franco", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Henrique Gaglionelli", categoria: "Sub-15-Masc", posicao: 7, pontos: 555 },
//     { atleta: "Luiz Guilherme", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Joao Pomato", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Miguel Soares", categoria: "Sub-15-Masc", posicao: 10, pontos: 488 },
//     { atleta: "Joao Teles", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Nathan De Olveira", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Nathan Silva", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
//     { atleta: "Matheus Ulrick", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
//     { atleta: "Julio Cesar", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
//     { atleta: "Leo Victor", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Joao Victor Lisboa", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Gabriel Ferreira", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Kayllon Miguel", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Julio Cezar", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Marco Antonio", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Nelvan Ferreira", categoria: "Sub-15-Masc", posicao: 19, pontos: 390 },
//     { atleta: "Irineu Correa", categoria: "Sub-15-Masc", posicao: 19, pontos: 390 },
//     { atleta: "Gabriel Aquino", categoria: "Sub-15-Masc", posicao: 19, pontos: 390 },
//     { atleta: "Arthur Leal", categoria: "Sub-15-Masc", posicao: 19, pontos: 390 },
//     { atleta: "Adailton Vieira", categoria: "Sub-15-Masc", posicao: 19, pontos: 390 },
// ];

// const resultadoSub15MascEtapa03New = [
//     { atleta: "Arthur Silva", categoria: "Sub-15-Masc", posicao: 5, pontos: 610 },
//     { atleta: "Noah Ribeiro", categoria: "Sub-15-Masc", posicao: 3, pontos: 730 },
//     { atleta: "Matheus Figueiredo", categoria: "Sub-15-Masc", posicao: 5, pontos: 610 },
//     { atleta: "Caio Henrique", categoria: "Sub-15-Masc", posicao: 1, pontos: 1000 },
//     { atleta: "Davi Carvalho", categoria: "Sub-15-Masc", posicao: 7, pontos: 555 },
//     { atleta: "Lucas Avellar", categoria: "Sub-15-Masc", posicao: 2, pontos: 860 },
//     { atleta: "Guilherme Almeida", categoria: "Sub-15-Masc", posicao: 4, pontos: 670 },
//     { atleta: "Arthur Carvalho", categoria: "Sub-15-Masc", posicao: 7, pontos: 555 },
//     { atleta: "Rafael Lorenzo", categoria: "Sub-15-Masc", posicao: 11, pontos: 475 },
//     { atleta: "Gael Chaves", categoria: "Sub-15-Masc", posicao: 11, pontos: 475 },
//     { atleta: "Nyas Chalfun", categoria: "Sub-15-Masc", posicao: 11, pontos: 475 },
//     { atleta: "Ryan Suricato", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Caua Guedes", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Guilherme Henrique", categoria: "Sub-15-Masc", posicao: 11, pontos: 475 },
//     { atleta: "Leyr Neto", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Yuri Franco", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Henrique Gaglionelli", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Luiz Guilherme", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Joao Pomato", categoria: "Sub-15-Masc", posicao: 7, pontos: 555 },
//     { atleta: "Miguel Soares", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Joao Teles", categoria: "Sub-15-Masc", posicao: 10, pontos: 488 },
//     { atleta: "Nathan De Olveira", categoria: "Sub-15-Masc", posicao: 11, pontos: 475 },
//     { atleta: "Nathan Silva", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Matheus Ulrick", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Julio Cesar", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Leo Victor", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Joao Victor Lisboa", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Gabriel Ferreira", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Kayllon Miguel", categoria: "Sub-15-Masc", posicao: 16, pontos: 413 },
//     { atleta: "Julio Cezar", categoria: "Sub-15-Masc", posicao: 16, pontos: 413 },
//     { atleta: "Marco Antonio", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Nelvan Ferreira", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Irineu Correa", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Gabriel Aquino", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Arthur Leal", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
//     { atleta: "Adailton Vieira", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
// ];

const resultadoProMascEtapa01New = [
  { atleta: "Adejaldo Silva", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Adriano Barreto", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Agatao Junior", categoria: "Pro-Masc", posicao: 17, pontos: 400 },
  {
    atleta: "Alexandre Silva",
    categoria: "Pro-Masc",
    posicao: 17,
    pontos: 400,
  },
  { atleta: "Andre Lopes", categoria: "Pro-Masc", posicao: 25, pontos: 360 },
  { atleta: "Andre Luiz", categoria: "Pro-Masc", posicao: 9, pontos: 500 },
  { atleta: "Andre Sancho", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Ariel Souza", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Arthur Patrick", categoria: "Pro-Masc", posicao: 25, pontos: 360 },
  { atleta: "Augusto Salvador", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Blademyr Capeloni",
    categoria: "Pro-Masc",
    posicao: 17,
    pontos: 400,
  },
  { atleta: "Bruno Araujo", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Bruno Leitao", categoria: "Pro-Masc", posicao: 25, pontos: 360 },
  { atleta: "Bruno Valente", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Caique Thomas", categoria: "Pro-Masc", posicao: 17, pontos: 400 },
  { atleta: "Carlos Bastos", categoria: "Pro-Masc", posicao: 9, pontos: 500 },
  {
    atleta: "Christopher Reis",
    categoria: "Pro-Masc",
    posicao: 17,
    pontos: 400,
  },
  { atleta: "Daniel Silva", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Diego Rodrigues", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Diogo Taboada", categoria: "Pro-Masc", posicao: 25, pontos: 360 },
  { atleta: "Dionatam Barroso", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Edson Junior", categoria: "Pro-Masc", posicao: 7, pontos: 555 },
  { atleta: "Erick Poseidon", categoria: "Pro-Masc", posicao: 9, pontos: 500 },
  {
    atleta: "Erisberto Abrantes",
    categoria: "Pro-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Felipe Lima", categoria: "Pro-Masc", posicao: 2, pontos: 860 },
  { atleta: "Felipe Pereira", categoria: "Pro-Masc", posicao: 25, pontos: 360 },
  { atleta: "Flavio Stanek", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Franklin Carlos", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Elizeu", categoria: "Pro-Masc", posicao: 13, pontos: 455 },
  { atleta: "Gabriel Flores", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Ramalho", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Rufino", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Gustavo Barreto",
    categoria: "Pro-Masc",
    posicao: 17,
    pontos: 400,
  },
  { atleta: "Igor Aboin", categoria: "Pro-Masc", posicao: 13, pontos: 455 },
  { atleta: "Israel Eduardo", categoria: "Pro-Masc", posicao: 1, pontos: 1000 },
  { atleta: "Joao Victor", categoria: "Pro-Masc", posicao: 13, pontos: 455 },
  { atleta: "Jose Otavio", categoria: "Pro-Masc", posicao: 3, pontos: 730 },
  { atleta: "Kaua Costa", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Leonardo Moreira",
    categoria: "Pro-Masc",
    posicao: 17,
    pontos: 400,
  },
  { atleta: "Lucas Figueiredo", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Lucas Franco", categoria: "Pro-Masc", posicao: 17, pontos: 400 },
  {
    atleta: "Matheus Figueiredo",
    categoria: "Pro-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Matheus Fontes", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Matheus Guimaraes",
    categoria: "Pro-Masc",
    posicao: 25,
    pontos: 360,
  },
  { atleta: "Maycon Cartaxo", categoria: "Pro-Masc", posicao: 25, pontos: 360 },
  { atleta: "Nicolas Araujo", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Paulo Victor Barros",
    categoria: "Pro-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Pedro Henrique", categoria: "Pro-Masc", posicao: 5, pontos: 610 },
  { atleta: "Rafael Paes", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Renan Biruleybe", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Renan Farias", categoria: "Pro-Masc", posicao: 9, pontos: 500 },
  {
    atleta: "Ricardo Andrade",
    categoria: "Pro-Masc",
    posicao: 25,
    pontos: 360,
  },
  { atleta: "Ricardo Junior", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Saul Felipe", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Sergio Machado", categoria: "Pro-Masc", posicao: 4, pontos: 670 },
  { atleta: "Shelton Icaro", categoria: "Pro-Masc", posicao: 13, pontos: 455 },
  { atleta: "Thiago Barros", categoria: "Pro-Masc", posicao: 5, pontos: 610 },
  { atleta: "Wardeley Junior", categoria: "Pro-Masc", posicao: 7, pontos: 555 },
  { atleta: "Yuri Sales", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
];

const resultadoProMascEtapa02New = [
  { atleta: "Adejaldo Silva", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Adriano Barreto", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Agatao Junior", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Alexandre Silva", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Andre Lopes", categoria: "Pro-Masc", posicao: 13, pontos: 455 },
  { atleta: "Andre Luiz", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Andre Sancho", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Ariel Souza", categoria: "Pro-Masc", posicao: 19, pontos: 390 },
  { atleta: "Arthur Patrick", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Augusto Salvador", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Blademyr Capeloni",
    categoria: "Pro-Masc",
    posicao: 9,
    pontos: 500,
  },
  { atleta: "Bruno Araujo", categoria: "Pro-Masc", posicao: 19, pontos: 390 },
  { atleta: "Bruno Leitao", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Bruno Valente", categoria: "Pro-Masc", posicao: 13, pontos: 455 },
  { atleta: "Caique Thomas", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Carlos Bastos", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Christopher Reis", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Daniel Silva", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Diego Rodrigues", categoria: "Pro-Masc", posicao: 7, pontos: 555 },
  { atleta: "Diogo Taboada", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Dionatam Barroso",
    categoria: "Pro-Masc",
    posicao: 13,
    pontos: 455,
  },
  { atleta: "Edson Junior", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Erick Poseidon", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Erisberto Abrantes",
    categoria: "Pro-Masc",
    posicao: 13,
    pontos: 455,
  },
  { atleta: "Felipe Lima", categoria: "Pro-Masc", posicao: 9, pontos: 500 },
  { atleta: "Felipe Pereira", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Flavio Stanek", categoria: "Pro-Masc", posicao: 9, pontos: 500 },
  {
    atleta: "Franklin Carlos",
    categoria: "Pro-Masc",
    posicao: 19,
    pontos: 390,
  },
  { atleta: "Gabriel Elizeu", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Flores", categoria: "Pro-Masc", posicao: 19, pontos: 390 },
  { atleta: "Gabriel Ramalho", categoria: "Pro-Masc", posicao: 9, pontos: 500 },
  { atleta: "Gabriel Rufino", categoria: "Pro-Masc", posicao: 5, pontos: 610 },
  { atleta: "Gustavo Barreto", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Igor Aboin", categoria: "Pro-Masc", posicao: 5, pontos: 610 },
  { atleta: "Israel Eduardo", categoria: "Pro-Masc", posicao: 3, pontos: 730 },
  { atleta: "Joao Victor", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Jose Otavio", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Kaua Costa", categoria: "Pro-Masc", posicao: 13, pontos: 455 },
  { atleta: "Leonardo Moreira", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Lucas Figueiredo", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Lucas Franco", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Matheus Figueiredo",
    categoria: "Pro-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Matheus Fontes", categoria: "Pro-Masc", posicao: 19, pontos: 390 },
  {
    atleta: "Matheus Guimaraes",
    categoria: "Pro-Masc",
    posicao: 13,
    pontos: 455,
  },
  { atleta: "Maycon Cartaxo", categoria: "Pro-Masc", posicao: 7, pontos: 555 },
  { atleta: "Nicolas Araujo", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Paulo Victor Barros",
    categoria: "Pro-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Pedro Henrique", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Rafael Paes", categoria: "Pro-Masc", posicao: 4, pontos: 670 },
  { atleta: "Renan Biruleybe", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Renan Farias", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Ricardo Andrade", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Ricardo Junior", categoria: "Pro-Masc", posicao: 19, pontos: 390 },
  { atleta: "Saul Felipe", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Sergio Machado", categoria: "Pro-Masc", posicao: 1, pontos: 1000 },
  { atleta: "Shelton Icaro", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Thiago Barros", categoria: "Pro-Masc", posicao: 2, pontos: 860 },
  { atleta: "Wardeley Junior", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Yuri Sales", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
];

const resultadoProMascEtapa03New = [
  { atleta: "Adejaldo Silva", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Adriano Barreto", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Agatao Junior", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Alexandre Silva",
    categoria: "Pro-Masc",
    posicao: 13,
    pontos: 455,
  },
  { atleta: "Andre Lopes", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Andre Luiz", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Andre Sancho", categoria: "Pro-Masc", posicao: 5, pontos: 610 },
  { atleta: "Ariel Souza", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Arthur Patrick", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Augusto Salvador", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Blademyr Capeloni",
    categoria: "Pro-Masc",
    posicao: 9,
    pontos: 500,
  },
  { atleta: "Bruno Araujo", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Bruno Leitao", categoria: "Pro-Masc", posicao: 9, pontos: 500 },
  { atleta: "Bruno Valente", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Caique Thomas", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Carlos Bastos", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Christopher Reis", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Daniel Silva", categoria: "Pro-Masc", posicao: 13, pontos: 455 },
  {
    atleta: "Diego Rodrigues",
    categoria: "Pro-Masc",
    posicao: 19,
    pontos: 390,
  },
  { atleta: "Diogo Taboada", categoria: "Pro-Masc", posicao: 5, pontos: 610 },
  { atleta: "Dionatam Barroso", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Edson Junior", categoria: "Pro-Masc", posicao: 1, pontos: 1000 },
  { atleta: "Erick Poseidon", categoria: "Pro-Masc", posicao: 13, pontos: 455 },
  {
    atleta: "Erisberto Abrantes",
    categoria: "Pro-Masc",
    posicao: 9,
    pontos: 500,
  },
  { atleta: "Felipe Lima", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Felipe Pereira", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Flavio Stanek", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Franklin Carlos",
    categoria: "Pro-Masc",
    posicao: 13,
    pontos: 455,
  },
  { atleta: "Gabriel Elizeu", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Flores", categoria: "Pro-Masc", posicao: 13, pontos: 455 },
  { atleta: "Gabriel Ramalho", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Rufino", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Gustavo Barreto", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Igor Aboin", categoria: "Pro-Masc", posicao: 2, pontos: 860 },
  { atleta: "Israel Eduardo", categoria: "Pro-Masc", posicao: 3, pontos: 730 },
  { atleta: "Joao Victor", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Jose Otavio", categoria: "Pro-Masc", posicao: 7, pontos: 555 },
  { atleta: "Kaua Costa", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Leonardo Moreira", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Lucas Figueiredo", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Lucas Franco", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Matheus Figueiredo",
    categoria: "Pro-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Matheus Fontes", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Matheus Guimaraes",
    categoria: "Pro-Masc",
    posicao: 13,
    pontos: 455,
  },
  { atleta: "Maycon Cartaxo", categoria: "Pro-Masc", posicao: 4, pontos: 670 },
  { atleta: "Nicolas Araujo", categoria: "Pro-Masc", posicao: 19, pontos: 390 },
  {
    atleta: "Paulo Victor Barros",
    categoria: "Pro-Masc",
    posicao: 19,
    pontos: 390,
  },
  { atleta: "Pedro Henrique", categoria: "Pro-Masc", posicao: 7, pontos: 555 },
  { atleta: "Rafael Paes", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Renan Biruleybe", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Renan Farias", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Ricardo Andrade", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Ricardo Junior", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Saul Felipe", categoria: "Pro-Masc", posicao: 19, pontos: 390 },
  { atleta: "Sergio Machado", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Shelton Icaro", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Thiago Barros", categoria: "Pro-Masc", posicao: 9, pontos: 500 },
  { atleta: "Wardeley Junior", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Yuri Sales", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
];

const resultadoProMascEtapa04New = [
  { atleta: "Adejaldo Silva", categoria: "Pro-Masc", posicao: 4, pontos: 670 },
  {
    atleta: "Adriano Barreto",
    categoria: "Pro-Masc",
    posicao: 13,
    pontos: 455,
  },
  { atleta: "Agatao Junior", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Alexandre Silva",
    categoria: "Pro-Masc",
    posicao: 13,
    pontos: 455,
  },
  { atleta: "Andre Lopes", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Andre Luiz", categoria: "Pro-Masc", posicao: 13, pontos: 455 },
  { atleta: "Andre Sancho", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Ariel Souza", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Arthur Patrick", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Augusto Salvador",
    categoria: "Pro-Masc",
    posicao: 19,
    pontos: 390,
  },
  {
    atleta: "Blademyr Capeloni",
    categoria: "Pro-Masc",
    posicao: 3,
    pontos: 730,
  },
  { atleta: "Bruno Araujo", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Bruno Leitao", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Bruno Valente", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Caique Thomas", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Carlos Bastos", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Christopher Reis", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Daniel Silva", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Diego Rodrigues",
    categoria: "Pro-Masc",
    posicao: 10,
    pontos: 488,
  },
  { atleta: "Diogo Taboada", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Dionatam Barroso", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Edson Junior", categoria: "Pro-Masc", posicao: 7, pontos: 555 },
  { atleta: "Erick Poseidon", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Erisberto Abrantes",
    categoria: "Pro-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Felipe Lima", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Felipe Pereira", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Flavio Stanek", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Franklin Carlos", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Elizeu", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Flores", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Ramalho", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Rufino", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Gustavo Barreto", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Igor Aboin", categoria: "Pro-Masc", posicao: 5, pontos: 610 },
  { atleta: "Israel Eduardo", categoria: "Pro-Masc", posicao: 1, pontos: 1000 },
  { atleta: "Joao Victor", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Jose Otavio", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Kaua Costa", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Leonardo Moreira", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Lucas Figueiredo",
    categoria: "Pro-Masc",
    posicao: 13,
    pontos: 455,
  },
  { atleta: "Lucas Franco", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Matheus Figueiredo",
    categoria: "Pro-Masc",
    posicao: 10,
    pontos: 488,
  },
  { atleta: "Matheus Fontes", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Matheus Guimaraes",
    categoria: "Pro-Masc",
    posicao: 10,
    pontos: 488,
  },
  { atleta: "Maycon Cartaxo", categoria: "Pro-Masc", posicao: 7, pontos: 555 },
  { atleta: "Nicolas Araujo", categoria: "Pro-Masc", posicao: 19, pontos: 390 },
  {
    atleta: "Paulo Victor Barros",
    categoria: "Pro-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Pedro Henrique", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Rafael Paes", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Renan Biruleybe", categoria: "Pro-Masc", posicao: 7, pontos: 555 },
  { atleta: "Renan Farias", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Ricardo Andrade", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Ricardo Junior", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Saul Felipe", categoria: "Pro-Masc", posicao: 13, pontos: 455 },
  { atleta: "Sergio Machado", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Shelton Icaro", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Thiago Barros", categoria: "Pro-Masc", posicao: 2, pontos: 860 },
  { atleta: "Wardeley Junior", categoria: "Pro-Masc", posicao: 0, pontos: 0 },
  { atleta: "Yuri Sales", categoria: "Pro-Masc", posicao: 5, pontos: 610 },
];

const resultadoProFemEtapa01New = [
  { atleta: "Victoria Moraes", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Paola Simao", categoria: "Pro-Fem", posicao: 1, pontos: 1000 },
  { atleta: "Melissa Souza", categoria: "Pro-Fem", posicao: 2, pontos: 860 },
  { atleta: "Bia Vieira", categoria: "Pro-Fem", posicao: 3, pontos: 730 },
  { atleta: "Bia Martins", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Sophia Veiga", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Isa Vidal", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Kamilla Video", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Yone Fernandes", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Izabel Fonseca", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Manoela Giacomassi", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
];

const resultadoProFemEtapa02New = [
  { atleta: "Victoria Moraes", categoria: "Pro-Fem", posicao: 2, pontos: 860 },
  { atleta: "Paola Simao", categoria: "Pro-Fem", posicao: 7, pontos: 555 },
  { atleta: "Melissa Souza", categoria: "Pro-Fem", posicao: 5, pontos: 610 },
  { atleta: "Bia Vieira", categoria: "Pro-Fem", posicao: 1, pontos: 1000 },
  { atleta: "Bia Martins", categoria: "Pro-Fem", posicao: 5, pontos: 610 },
  { atleta: "Sophia Veiga", categoria: "Pro-Fem", posicao: 7, pontos: 555 },
  { atleta: "Isa Vidal", categoria: "Pro-Fem", posicao: 3, pontos: 730 },
  { atleta: "Kamilla Video", categoria: "Pro-Fem", posicao: 4, pontos: 670 },
  { atleta: "Yone Fernandes", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Izabel Fonseca", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  {
    atleta: "Manoela Giacomassi",
    categoria: "Pro-Fem",
    posicao: 7,
    pontos: 555,
  },
];

const resultadoProFemEtapa03New = [
  { atleta: "Victoria Moraes", categoria: "Pro-Fem", posicao: 1, pontos: 1000 },
  { atleta: "Paola Simao", categoria: "Pro-Fem", posicao: 2, pontos: 860 },
  { atleta: "Melissa Souza", categoria: "Pro-Fem", posicao: 3, pontos: 730 },
  { atleta: "Bia Vieira", categoria: "Pro-Fem", posicao: 4, pontos: 670 },
  { atleta: "Bia Martins", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Sophia Veiga", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Isa Vidal", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Kamilla Video", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Yone Fernandes", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Izabel Fonseca", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Manoela Giacomassi", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
];

const resultadoProFemEtapa04New = [
  { atleta: "Victoria Moraes", categoria: "Pro-Fem", posicao: 1, pontos: 1000 },
  { atleta: "Paola Simao", categoria: "Pro-Fem", posicao: 3, pontos: 730 },
  { atleta: "Melissa Souza", categoria: "Pro-Fem", posicao: 2, pontos: 860 },
  { atleta: "Bia Vieira", categoria: "Pro-Fem", posicao: 4, pontos: 670 },
  { atleta: "Bia Martins", categoria: "Pro-Fem", posicao: 7, pontos: 555 },
  { atleta: "Sophia Veiga", categoria: "Pro-Fem", posicao: 5, pontos: 610 },
  { atleta: "Isa Vidal", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Kamilla Video", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
  { atleta: "Yone Fernandes", categoria: "Pro-Fem", posicao: 5, pontos: 610 },
  { atleta: "Izabel Fonseca", categoria: "Pro-Fem", posicao: 7, pontos: 555 },
  { atleta: "Manoela Giacomassi", categoria: "Pro-Fem", posicao: 0, pontos: 0 },
];

// insert new results here
const resultadoMasterEtapa01New = [
  { atleta: "Gugu Barcellos", categoria: "Master", posicao: 4, pontos: 670 },
  { atleta: "Joaquim Carvalho", categoria: "Master", posicao: 2, pontos: 860 },
  { atleta: "Felipe Colombo", categoria: "Master", posicao: 1, pontos: 1000 },
  { atleta: "Andre Paiva", categoria: "Master", posicao: 9, pontos: 500 },
  {
    atleta: "Paulo Victor Barros",
    categoria: "Master",
    posicao: 7,
    pontos: 555,
  },
  { atleta: "Diogo Taboada", categoria: "Master", posicao: 3, pontos: 730 },
  { atleta: "Dennys Rosa", categoria: "Master", posicao: 9, pontos: 500 },
  { atleta: "Antonio Japa", categoria: "Master", posicao: 13, pontos: 450 },
  {
    atleta: "Cristiano Freitas",
    categoria: "Master",
    posicao: 13,
    pontos: 450,
  },
  { atleta: "Erisberto Abrantes", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Erick Poseidon", categoria: "Master", posicao: 9, pontos: 500 },
  { atleta: "Dudu Almeida", categoria: "Master", posicao: 5, pontos: 610 },
  { atleta: "Franklin Carlos", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Milton Agatao", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Gil Alexandre", categoria: "Master", posicao: 13, pontos: 450 },
  { atleta: "Alex Kundera", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Thiago Siqueira", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Sandro Justo", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Adriano Minguta", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Leandro Moreira", categoria: "Master", posicao: 5, pontos: 610 },
  { atleta: "Hugo Aurelio", categoria: "Master", posicao: 7, pontos: 555 },
  { atleta: "Bruno Ross", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Fernando Almeida", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Felipe Santiago", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Zacaro", categoria: "Master", posicao: 9, pontos: 500 },
  { atleta: "Leo Santana", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Guilherme Batista", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Felipe Soares", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Sandro Melo", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Bruno Augusto", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Alexandre Ramos", categoria: "Master", posicao: 0, pontos: 0 },
];

const resultadoMasterEtapa02New = [
  { atleta: "Gugu Barcellos", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Joaquim Carvalho", categoria: "Master", posicao: 3, pontos: 730 },
  { atleta: "Felipe Colombo", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Andre Paiva", categoria: "Master", posicao: 7, pontos: 555 },
  {
    atleta: "Paulo Victor Barros",
    categoria: "Master",
    posicao: 2,
    pontos: 860,
  },
  { atleta: "Diogo Taboada", categoria: "Master", posicao: 5, pontos: 610 },
  { atleta: "Dennys Rosa", categoria: "Master", posicao: 4, pontos: 670 },
  { atleta: "Antonio Japa", categoria: "Master", posicao: 7, pontos: 555 },
  {
    atleta: "Cristiano Freitas",
    categoria: "Master",
    posicao: 13,
    pontos: 450,
  },
  {
    atleta: "Erisberto Abrantes",
    categoria: "Master",
    posicao: 1,
    pontos: 1000,
  },
  { atleta: "Erick Poseidon", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Dudu Almeida", categoria: "Master", posicao: 9, pontos: 500 },
  { atleta: "Franklin Carlos", categoria: "Master", posicao: 9, pontos: 500 },
  { atleta: "Milton Agatao", categoria: "Master", posicao: 9, pontos: 500 },
  { atleta: "Gil Alexandre", categoria: "Master", posicao: 13, pontos: 450 },
  { atleta: "Alex Kundera", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Thiago Siqueira", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Sandro Justo", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Adriano Minguta", categoria: "Master", posicao: 5, pontos: 610 },
  { atleta: "Leandro Moreira", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Hugo Aurelio", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Bruno Ross", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Fernando Almeida", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Felipe Santiago", categoria: "Master", posicao: 9, pontos: 500 },
  { atleta: "Gabriel Zacaro", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Leo Santana", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Guilherme Batista", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Felipe Soares", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Sandro Melo", categoria: "Master", posicao: 13, pontos: 450 },
  { atleta: "Bruno Augusto", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Alexandre Ramos", categoria: "Master", posicao: 13, pontos: 450 },
];

const resultadoMasterEtapa03New = [
  { atleta: "Gugu Barcellos", categoria: "Master", posicao: 3, pontos: 730 },
  { atleta: "Joaquim Carvalho", categoria: "Master", posicao: 4, pontos: 670 },
  { atleta: "Felipe Colombo", categoria: "Master", posicao: 7, pontos: 555 },
  { atleta: "Andre Paiva", categoria: "Master", posicao: 1, pontos: 1000 },
  {
    atleta: "Paulo Victor Barros",
    categoria: "Master",
    posicao: 9,
    pontos: 500,
  },
  { atleta: "Diogo Taboada", categoria: "Master", posicao: 9, pontos: 500 },
  { atleta: "Dennys Rosa", categoria: "Master", posicao: 13, pontos: 450 },
  { atleta: "Antonio Japa", categoria: "Master", posicao: 13, pontos: 450 },
  { atleta: "Cristiano Freitas", categoria: "Master", posicao: 5, pontos: 610 },
  {
    atleta: "Erisberto Abrantes",
    categoria: "Master",
    posicao: 9,
    pontos: 500,
  },
  { atleta: "Erick Poseidon", categoria: "Master", posicao: 2, pontos: 860 },
  { atleta: "Dudu Almeida", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Franklin Carlos", categoria: "Master", posicao: 7, pontos: 555 },
  { atleta: "Milton Agatao", categoria: "Master", posicao: 13, pontos: 450 },
  { atleta: "Gil Alexandre", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Alex Kundera", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Thiago Siqueira", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Sandro Justo", categoria: "Master", posicao: 5, pontos: 610 },
  { atleta: "Adriano Minguta", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Leandro Moreira", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Hugo Aurelio", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Bruno Ross", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Fernando Almeida", categoria: "Master", posicao: 9, pontos: 500 },
  { atleta: "Felipe Santiago", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Zacaro", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Leo Santana", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Guilherme Batista", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Felipe Soares", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Sandro Melo", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Bruno Augusto", categoria: "Master", posicao: 13, pontos: 450 },
  { atleta: "Alexandre Ramos", categoria: "Master", posicao: 0, pontos: 0 },
];

const resultadoMasterEtapa04New = [
  { atleta: "Gugu Barcellos", categoria: "Master", posicao: 1, pontos: 1000 },
  { atleta: "Joaquim Carvalho", categoria: "Master", posicao: 3, pontos: 730 },
  { atleta: "Felipe Colombo", categoria: "Master", posicao: 4, pontos: 670 },
  { atleta: "Andre Paiva", categoria: "Master", posicao: 7, pontos: 555 },
  { atleta: "Paulo Victor Barros", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Diogo Taboada", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Dennys Rosa", categoria: "Master", posicao: 5, pontos: 610 },
  { atleta: "Antonio Japa", categoria: "Master", posicao: 7, pontos: 555 },
  { atleta: "Cristiano Freitas", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Erisberto Abrantes", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Erick Poseidon", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Dudu Almeida", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Franklin Carlos", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Milton Agatao", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Gil Alexandre", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Alex Kundera", categoria: "Master", posicao: 2, pontos: 860 },
  { atleta: "Thiago Siqueira", categoria: "Master", posicao: 5, pontos: 610 },
  { atleta: "Sandro Justo", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Adriano Minguta", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Leandro Moreira", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Hugo Aurelio", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Bruno Ross", categoria: "Master", posicao: 7, pontos: 555 },
  { atleta: "Fernando Almeida", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Felipe Santiago", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Zacaro", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Leo Santana", categoria: "Master", posicao: 10, pontos: 488 },
  {
    atleta: "Guilherme Batista",
    categoria: "Master",
    posicao: 10,
    pontos: 488,
  },
  { atleta: "Felipe Soares", categoria: "Master", posicao: 10, pontos: 488 },
  { atleta: "Sandro Melo", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Bruno Augusto", categoria: "Master", posicao: 0, pontos: 0 },
  { atleta: "Alexandre Ramos", categoria: "Master", posicao: 0, pontos: 0 },
];

const resultadoLegendEtapa01New = [
  { atleta: "Gugu Barcellos", categoria: "Legend", posicao: 1, pontos: 1000 },
  { atleta: "Andre Paiva", categoria: "Legend", posicao: 5, pontos: 610 },
  { atleta: "Ivan Brandao", categoria: "Legend", posicao: 2, pontos: 860 },
  { atleta: "Dennys Rosa", categoria: "Legend", posicao: 7, pontos: 555 },
  { atleta: "Marcelo Muniz", categoria: "Legend", posicao: 3, pontos: 730 },
  { atleta: "Fabio Henrique", categoria: "Legend", posicao: 10, pontos: 488 },
  { atleta: "Wagner Gouveia", categoria: "Legend", posicao: 7, pontos: 555 },
  { atleta: "Rafael Dorileo", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Sergio Castanheira", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Alex Kundera", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Pierre Junior", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Jose Otavio", categoria: "Legend", posicao: 4, pontos: 670 },
  { atleta: "Gabriel Zacaro", categoria: "Legend", posicao: 5, pontos: 610 },
  { atleta: "Alexandre Ramos", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Rodrigo Correia", categoria: "Legend", posicao: 7, pontos: 555 },
  { atleta: "Milton Agatao", categoria: "Legend", posicao: 10, pontos: 488 },
  { atleta: "Forlan Custodio", categoria: "Legend", posicao: 10, pontos: 488 },
];

const resultadoLegendEtapa02New = [
  { atleta: "Gugu Barcellos", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Andre Paiva", categoria: "Legend", posicao: 3, pontos: 730 },
  { atleta: "Ivan Brandao", categoria: "Legend", posicao: 2, pontos: 860 },
  { atleta: "Dennys Rosa", categoria: "Legend", posicao: 1, pontos: 1000 },
  { atleta: "Marcelo Muniz", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Fabio Henrique", categoria: "Legend", posicao: 5, pontos: 610 },
  { atleta: "Wagner Gouveia", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Rafael Dorileo", categoria: "Legend", posicao: 4, pontos: 670 },
  {
    atleta: "Sergio Castanheira",
    categoria: "Legend",
    posicao: 5,
    pontos: 610,
  },
  { atleta: "Alex Kundera", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Pierre Junior", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Jose Otavio", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Zacaro", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Alexandre Ramos", categoria: "Legend", posicao: 7, pontos: 555 },
  { atleta: "Rodrigo Correia", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Milton Agatao", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Forlan Custodio", categoria: "Legend", posicao: 0, pontos: 0 },
];

const resultadoLegendEtapa03New = [
  { atleta: "Gugu Barcellos", categoria: "Legend", posicao: 1, pontos: 1000 },
  { atleta: "Andre Paiva", categoria: "Legend", posicao: 2, pontos: 860 },
  { atleta: "Ivan Brandao", categoria: "Legend", posicao: 7, pontos: 555 },
  { atleta: "Dennys Rosa", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Marcelo Muniz", categoria: "Legend", posicao: 3, pontos: 730 },
  { atleta: "Fabio Henrique", categoria: "Legend", posicao: 5, pontos: 610 },
  { atleta: "Wagner Gouveia", categoria: "Legend", posicao: 4, pontos: 670 },
  { atleta: "Rafael Dorileo", categoria: "Legend", posicao: 5, pontos: 610 },
  { atleta: "Sergio Castanheira", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Alex Kundera", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Pierre Junior", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Jose Otavio", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Zacaro", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Alexandre Ramos", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Rodrigo Correia", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Milton Agatao", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Forlan Custodio", categoria: "Legend", posicao: 0, pontos: 0 },
];

const resultadoLegendEtapa04New = [
  { atleta: "Gugu Barcellos", categoria: "Legend", posicao: 1, pontos: 1000 },
  { atleta: "Andre Paiva", categoria: "Legend", posicao: 3, pontos: 730 },
  { atleta: "Ivan Brandao", categoria: "Legend", posicao: 7, pontos: 555 },
  { atleta: "Dennys Rosa", categoria: "Legend", posicao: 5, pontos: 610 },
  { atleta: "Marcelo Muniz", categoria: "Legend", posicao: 5, pontos: 610 },
  { atleta: "Fabio Henrique", categoria: "Legend", posicao: 7, pontos: 555 },
  { atleta: "Wagner Gouveia", categoria: "Legend", posicao: 10, pontos: 488 },
  { atleta: "Rafael Dorileo", categoria: "Legend", posicao: 0, pontos: 0 },
  {
    atleta: "Sergio Castanheira",
    categoria: "Legend",
    posicao: 7,
    pontos: 555,
  },
  { atleta: "Alex Kundera", categoria: "Legend", posicao: 2, pontos: 860 },
  { atleta: "Pierre Junior", categoria: "Legend", posicao: 4, pontos: 670 },
  { atleta: "Jose Otavio", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Zacaro", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Alexandre Ramos", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Rodrigo Correia", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Milton Agatao", categoria: "Legend", posicao: 0, pontos: 0 },
  { atleta: "Forlan Custodio", categoria: "Legend", posicao: 0, pontos: 0 },
];

const resultadoSub15FemEtapa01New = [
  { atleta: "Sophia Veiga", categoria: "Sub-15-Fem", posicao: 0, pontos: 0 },
  {
    atleta: "Yone Fernandes",
    categoria: "Sub-15-Fem",
    posicao: 1,
    pontos: 1000,
  },
  { atleta: "Alyne Moreira", categoria: "Sub-15-Fem", posicao: 0, pontos: 0 },
  { atleta: "Larissa Brandao", categoria: "Sub-15-Fem", posicao: 0, pontos: 0 },
  { atleta: "Sofia Goncalves", categoria: "Sub-15-Fem", posicao: 0, pontos: 0 },
  {
    atleta: "Micaelly Oliveira",
    categoria: "Sub-15-Fem",
    posicao: 2,
    pontos: 860,
  },
  { atleta: "Maria Julia", categoria: "Sub-15-Fem", posicao: 0, pontos: 0 },
  {
    atleta: "Gabriela Oliveira",
    categoria: "Sub-15-Fem",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Emily Alves", categoria: "Sub-15-Fem", posicao: 0, pontos: 0 },
  { atleta: "Alice Fonseca", categoria: "Sub-15-Fem", posicao: 0, pontos: 0 },
  {
    atleta: "Ana Luiza Mangeli",
    categoria: "Sub-15-Fem",
    posicao: 0,
    pontos: 0,
  },
];

const resultadoSub15FemEtapa02New = [
  { atleta: "Sophia Veiga", categoria: "Sub-15-Fem", posicao: 1, pontos: 1000 },
  { atleta: "Yone Fernandes", categoria: "Sub-15-Fem", posicao: 0, pontos: 0 },
  { atleta: "Alyne Moreira", categoria: "Sub-15-Fem", posicao: 3, pontos: 730 },
  {
    atleta: "Larissa Brandao",
    categoria: "Sub-15-Fem",
    posicao: 5,
    pontos: 610,
  },
  {
    atleta: "Sofia Goncalves",
    categoria: "Sub-15-Fem",
    posicao: 2,
    pontos: 860,
  },
  {
    atleta: "Micaelly Oliveira",
    categoria: "Sub-15-Fem",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Maria Julia", categoria: "Sub-15-Fem", posicao: 0, pontos: 0 },
  {
    atleta: "Gabriela Oliveira",
    categoria: "Sub-15-Fem",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Emily Alves", categoria: "Sub-15-Fem", posicao: 4, pontos: 670 },
  { atleta: "Alice Fonseca", categoria: "Sub-15-Fem", posicao: 5, pontos: 610 },
  {
    atleta: "Ana Luiza Mangeli",
    categoria: "Sub-15-Fem",
    posicao: 0,
    pontos: 0,
  },
];

const resultadoSub15FemEtapa03New = [
  { atleta: "Sophia Veiga", categoria: "Sub-15-Fem", posicao: 1, pontos: 1000 },
  {
    atleta: "Yone Fernandes",
    categoria: "Sub-15-Fem",
    posicao: 2,
    pontos: 860,
  },
  { atleta: "Alyne Moreira", categoria: "Sub-15-Fem", posicao: 5, pontos: 610 },
  {
    atleta: "Larissa Brandao",
    categoria: "Sub-15-Fem",
    posicao: 5,
    pontos: 610,
  },
  { atleta: "Sofia Goncalves", categoria: "Sub-15-Fem", posicao: 0, pontos: 0 },
  {
    atleta: "Micaelly Oliveira",
    categoria: "Sub-15-Fem",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Maria Julia", categoria: "Sub-15-Fem", posicao: 3, pontos: 730 },
  {
    atleta: "Gabriela Oliveira",
    categoria: "Sub-15-Fem",
    posicao: 4,
    pontos: 670,
  },
  { atleta: "Emily Alves", categoria: "Sub-15-Fem", posicao: 0, pontos: 0 },
  { atleta: "Alice Fonseca", categoria: "Sub-15-Fem", posicao: 0, pontos: 0 },
  {
    atleta: "Ana Luiza Mangeli",
    categoria: "Sub-15-Fem",
    posicao: 7,
    pontos: 555,
  },
];

const resultadoSub15MascEtapa01New = [
  {
    atleta: "Arthur Silva",
    categoria: "Sub-15-Masc",
    posicao: 1,
    pontos: 1000,
  },
  { atleta: "Noah Ribeiro", categoria: "Sub-15-Masc", posicao: 7, pontos: 555 },
  {
    atleta: "Matheus Figueiredo",
    categoria: "Sub-15-Masc",
    posicao: 3,
    pontos: 730,
  },
  {
    atleta: "Caio Henrique",
    categoria: "Sub-15-Masc",
    posicao: 5,
    pontos: 610,
  },
  {
    atleta: "Davi Carvalho",
    categoria: "Sub-15-Masc",
    posicao: 2,
    pontos: 860,
  },
  {
    atleta: "Lucas Avellar",
    categoria: "Sub-15-Masc",
    posicao: 13,
    pontos: 450,
  },
  {
    atleta: "Guilherme Almeida",
    categoria: "Sub-15-Masc",
    posicao: 7,
    pontos: 555,
  },
  {
    atleta: "Arthur Carvalho",
    categoria: "Sub-15-Masc",
    posicao: 10,
    pontos: 488,
  },
  {
    atleta: "Rafael Lorenzo",
    categoria: "Sub-15-Masc",
    posicao: 13,
    pontos: 450,
  },
  { atleta: "Gael Chaves", categoria: "Sub-15-Masc", posicao: 5, pontos: 610 },
  { atleta: "Nyas Chalfun", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Ryan Suricato",
    categoria: "Sub-15-Masc",
    posicao: 10,
    pontos: 488,
  },
  { atleta: "Caua Guedes", categoria: "Sub-15-Masc", posicao: 10, pontos: 488 },
  {
    atleta: "Guilherme Henrique",
    categoria: "Sub-15-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Leyr Neto", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
  { atleta: "Yuri Franco", categoria: "Sub-15-Masc", posicao: 4, pontos: 670 },
  {
    atleta: "Henrique Gaglionelli",
    categoria: "Sub-15-Masc",
    posicao: 0,
    pontos: 0,
  },
  {
    atleta: "Luiz Guilherme",
    categoria: "Sub-15-Masc",
    posicao: 7,
    pontos: 555,
  },
  { atleta: "Joao Pomato", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Miguel Soares", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Joao Teles", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Nathan De Olveira",
    categoria: "Sub-15-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Nathan Silva", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Matheus Ulrick", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Julio Cesar", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Leo Victor", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
  {
    atleta: "Joao Victor Lisboa",
    categoria: "Sub-15-Masc",
    posicao: 13,
    pontos: 450,
  },
  {
    atleta: "Gabriel Ferreira",
    categoria: "Sub-15-Masc",
    posicao: 13,
    pontos: 450,
  },
  { atleta: "Kayllon Miguel", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Julio Cezar", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Marco Antonio", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Nelvan Ferreira",
    categoria: "Sub-15-Masc",
    posicao: 19,
    pontos: 390,
  },
  {
    atleta: "Irineu Correa",
    categoria: "Sub-15-Masc",
    posicao: 19,
    pontos: 390,
  },
  {
    atleta: "Gabriel Aquino",
    categoria: "Sub-15-Masc",
    posicao: 19,
    pontos: 390,
  },
  { atleta: "Arthur Leal", categoria: "Sub-15-Masc", posicao: 19, pontos: 390 },
  {
    atleta: "Adailton Vieira",
    categoria: "Sub-15-Masc",
    posicao: 19,
    pontos: 390,
  },
];

const resultadoSub15MascEtapa02New = [
  { atleta: "Arthur Silva", categoria: "Sub-15-Masc", posicao: 3, pontos: 730 },
  {
    atleta: "Noah Ribeiro",
    categoria: "Sub-15-Masc",
    posicao: 1,
    pontos: 1000,
  },
  {
    atleta: "Matheus Figueiredo",
    categoria: "Sub-15-Masc",
    posicao: 2,
    pontos: 860,
  },
  {
    atleta: "Caio Henrique",
    categoria: "Sub-15-Masc",
    posicao: 13,
    pontos: 450,
  },
  {
    atleta: "Davi Carvalho",
    categoria: "Sub-15-Masc",
    posicao: 7,
    pontos: 555,
  },
  {
    atleta: "Lucas Avellar",
    categoria: "Sub-15-Masc",
    posicao: 5,
    pontos: 610,
  },
  {
    atleta: "Guilherme Almeida",
    categoria: "Sub-15-Masc",
    posicao: 4,
    pontos: 670,
  },
  {
    atleta: "Arthur Carvalho",
    categoria: "Sub-15-Masc",
    posicao: 5,
    pontos: 610,
  },
  {
    atleta: "Rafael Lorenzo",
    categoria: "Sub-15-Masc",
    posicao: 13,
    pontos: 450,
  },
  { atleta: "Gael Chaves", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Nyas Chalfun", categoria: "Sub-15-Masc", posicao: 7, pontos: 555 },
  {
    atleta: "Ryan Suricato",
    categoria: "Sub-15-Masc",
    posicao: 10,
    pontos: 488,
  },
  { atleta: "Caua Guedes", categoria: "Sub-15-Masc", posicao: 10, pontos: 488 },
  {
    atleta: "Guilherme Henrique",
    categoria: "Sub-15-Masc",
    posicao: 13,
    pontos: 450,
  },
  { atleta: "Leyr Neto", categoria: "Sub-15-Masc", posicao: 19, pontos: 390 },
  { atleta: "Yuri Franco", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Henrique Gaglionelli",
    categoria: "Sub-15-Masc",
    posicao: 7,
    pontos: 555,
  },
  { atleta: "Luiz Guilherme", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Joao Pomato", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Miguel Soares",
    categoria: "Sub-15-Masc",
    posicao: 10,
    pontos: 488,
  },
  { atleta: "Joao Teles", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Nathan De Olveira",
    categoria: "Sub-15-Masc",
    posicao: 0,
    pontos: 0,
  },
  {
    atleta: "Nathan Silva",
    categoria: "Sub-15-Masc",
    posicao: 13,
    pontos: 450,
  },
  {
    atleta: "Matheus Ulrick",
    categoria: "Sub-15-Masc",
    posicao: 13,
    pontos: 450,
  },
  { atleta: "Julio Cesar", categoria: "Sub-15-Masc", posicao: 13, pontos: 450 },
  { atleta: "Leo Victor", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Joao Victor Lisboa",
    categoria: "Sub-15-Masc",
    posicao: 0,
    pontos: 0,
  },
  {
    atleta: "Gabriel Ferreira",
    categoria: "Sub-15-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Kayllon Miguel", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Julio Cezar", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Marco Antonio",
    categoria: "Sub-15-Masc",
    posicao: 19,
    pontos: 390,
  },
  {
    atleta: "Nelvan Ferreira",
    categoria: "Sub-15-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Irineu Correa", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Aquino", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Arthur Leal", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Adailton Vieira",
    categoria: "Sub-15-Masc",
    posicao: 0,
    pontos: 0,
  },
];

const resultadoSub15MascEtapa03New = [
  { atleta: "Arthur Silva", categoria: "Sub-15-Masc", posicao: 5, pontos: 610 },
  { atleta: "Noah Ribeiro", categoria: "Sub-15-Masc", posicao: 3, pontos: 730 },
  {
    atleta: "Matheus Figueiredo",
    categoria: "Sub-15-Masc",
    posicao: 5,
    pontos: 610,
  },
  {
    atleta: "Caio Henrique",
    categoria: "Sub-15-Masc",
    posicao: 1,
    pontos: 1000,
  },
  {
    atleta: "Davi Carvalho",
    categoria: "Sub-15-Masc",
    posicao: 7,
    pontos: 555,
  },
  {
    atleta: "Lucas Avellar",
    categoria: "Sub-15-Masc",
    posicao: 2,
    pontos: 860,
  },
  {
    atleta: "Guilherme Almeida",
    categoria: "Sub-15-Masc",
    posicao: 4,
    pontos: 670,
  },
  {
    atleta: "Arthur Carvalho",
    categoria: "Sub-15-Masc",
    posicao: 7,
    pontos: 555,
  },
  {
    atleta: "Rafael Lorenzo",
    categoria: "Sub-15-Masc",
    posicao: 11,
    pontos: 475,
  },
  { atleta: "Gael Chaves", categoria: "Sub-15-Masc", posicao: 11, pontos: 475 },
  {
    atleta: "Nyas Chalfun",
    categoria: "Sub-15-Masc",
    posicao: 11,
    pontos: 475,
  },
  { atleta: "Ryan Suricato", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Caua Guedes", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Guilherme Henrique",
    categoria: "Sub-15-Masc",
    posicao: 11,
    pontos: 475,
  },
  { atleta: "Leyr Neto", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Yuri Franco", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Henrique Gaglionelli",
    categoria: "Sub-15-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Luiz Guilherme", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Joao Pomato", categoria: "Sub-15-Masc", posicao: 7, pontos: 555 },
  { atleta: "Miguel Soares", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Joao Teles", categoria: "Sub-15-Masc", posicao: 10, pontos: 488 },
  {
    atleta: "Nathan De Olveira",
    categoria: "Sub-15-Masc",
    posicao: 11,
    pontos: 475,
  },
  { atleta: "Nathan Silva", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Matheus Ulrick", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Julio Cesar", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Leo Victor", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Joao Victor Lisboa",
    categoria: "Sub-15-Masc",
    posicao: 0,
    pontos: 0,
  },
  {
    atleta: "Gabriel Ferreira",
    categoria: "Sub-15-Masc",
    posicao: 0,
    pontos: 0,
  },
  {
    atleta: "Kayllon Miguel",
    categoria: "Sub-15-Masc",
    posicao: 16,
    pontos: 413,
  },
  { atleta: "Julio Cezar", categoria: "Sub-15-Masc", posicao: 16, pontos: 413 },
  { atleta: "Marco Antonio", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Nelvan Ferreira",
    categoria: "Sub-15-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Irineu Correa", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Gabriel Aquino", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  { atleta: "Arthur Leal", categoria: "Sub-15-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Adailton Vieira",
    categoria: "Sub-15-Masc",
    posicao: 0,
    pontos: 0,
  },
];

const resultadoSub12MascEtapa01New = [
  { atleta: "Nyas Chalfun", categoria: "Sub-12-Masc", posicao: 3, pontos: 730 },
  {
    atleta: "David Martins",
    categoria: "Sub-12-Masc",
    posicao: 4,
    pontos: 670,
  },
  {
    atleta: "Henrique Gaglionelli",
    categoria: "Sub-12-Masc",
    posicao: 1,
    pontos: 1000,
  },
  {
    atleta: "Lucca Garcia",
    categoria: "Sub-12-Masc",
    posicao: 13,
    pontos: 450,
  },
  { atleta: "Bernardo Brito", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Rafael Silva", categoria: "Sub-12-Masc", posicao: 2, pontos: 860 },
  { atleta: "Miguel Silva", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Vitinho", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Lucas Alcantara",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
  {
    atleta: "Vinicius Nascimento",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Lucas Coelho", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Guilherme Perre",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
  {
    atleta: "Enzo Cabreira",
    categoria: "Sub-12-Masc",
    posicao: 5,
    pontos: 610,
  },
  {
    atleta: "Brayan Martins",
    categoria: "Sub-12-Masc",
    posicao: 5,
    pontos: 610,
  },
  { atleta: "Ravi Falcon", categoria: "Sub-12-Masc", posicao: 7, pontos: 555 },
  {
    atleta: "Pedro Da Silva",
    categoria: "Sub-12-Masc",
    posicao: 7,
    pontos: 555,
  },
  {
    atleta: "Joao Victor Novak",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Caio Lucas", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Bernardo Dos Anjos",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Tomze Muller", categoria: "Sub-12-Masc", posicao: 9, pontos: 500 },
  {
    atleta: "Nicolas Chalfun",
    categoria: "Sub-12-Masc",
    posicao: 9,
    pontos: 500,
  },
  { atleta: "Joao Marins", categoria: "Sub-12-Masc", posicao: 9, pontos: 500 },
  {
    atleta: "Augusto Sigle",
    categoria: "Sub-12-Masc",
    posicao: 9,
    pontos: 500,
  },
  { atleta: "Carlos Eduardo", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Davi Carvalho Barbosa",
    categoria: "Sub-12-Masc",
    posicao: 13,
    pontos: 450,
  },
];

const resultadoSub12MascEtapa02New = [
  {
    atleta: "Nyas Chalfun",
    categoria: "Sub-12-Masc",
    posicao: 1,
    pontos: 1000,
  },
  {
    atleta: "David Martins",
    categoria: "Sub-12-Masc",
    posicao: 3,
    pontos: 730,
  },
  {
    atleta: "Henrique Gaglionelli",
    categoria: "Sub-12-Masc",
    posicao: 2,
    pontos: 860,
  },
  { atleta: "Lucca Garcia", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Bernardo Brito", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Rafael Silva", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Miguel Silva", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Vitinho", categoria: "Sub-12-Masc", posicao: 4, pontos: 670 },
  {
    atleta: "Lucas Alcantara",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
  {
    atleta: "Vinicius Nascimento",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Lucas Coelho", categoria: "Sub-12-Masc", posicao: 5, pontos: 610 },
  {
    atleta: "Guilherme Perre",
    categoria: "Sub-12-Masc",
    posicao: 5,
    pontos: 610,
  },
  { atleta: "Enzo Cabreira", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Brayan Martins", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Ravi Falcon", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Pedro Da Silva", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Joao Victor Novak",
    categoria: "Sub-12-Masc",
    posicao: 7,
    pontos: 555,
  },
  { atleta: "Caio Lucas", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Bernardo Dos Anjos",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Tomze Muller", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Nicolas Chalfun",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Joao Marins", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Augusto Sigle", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Carlos Eduardo", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Davi Carvalho Barbosa",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
];

const resultadoSub12MascEtapa03New = [
  { atleta: "Nyas Chalfun", categoria: "Sub-12-Masc", posicao: 2, pontos: 860 },
  {
    atleta: "David Martins",
    categoria: "Sub-12-Masc",
    posicao: 7,
    pontos: 555,
  },
  {
    atleta: "Henrique Gaglionelli",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Lucca Garcia", categoria: "Sub-12-Masc", posicao: 5, pontos: 610 },
  {
    atleta: "Bernardo Brito",
    categoria: "Sub-12-Masc",
    posicao: 1,
    pontos: 1000,
  },
  { atleta: "Rafael Silva", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Miguel Silva", categoria: "Sub-12-Masc", posicao: 3, pontos: 730 },
  { atleta: "Vitinho", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Lucas Alcantara",
    categoria: "Sub-12-Masc",
    posicao: 4,
    pontos: 670,
  },
  {
    atleta: "Vinicius Nascimento",
    categoria: "Sub-12-Masc",
    posicao: 5,
    pontos: 610,
  },
  { atleta: "Lucas Coelho", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Guilherme Perre",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Enzo Cabreira", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Brayan Martins", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Ravi Falcon", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Pedro Da Silva", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Joao Victor Novak",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Caio Lucas", categoria: "Sub-12-Masc", posicao: 7, pontos: 555 },
  {
    atleta: "Bernardo Dos Anjos",
    categoria: "Sub-12-Masc",
    posicao: 7,
    pontos: 555,
  },
  { atleta: "Tomze Muller", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Nicolas Chalfun",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Joao Marins", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  { atleta: "Augusto Sigle", categoria: "Sub-12-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Carlos Eduardo",
    categoria: "Sub-12-Masc",
    posicao: 10,
    pontos: 488,
  },
  {
    atleta: "Davi Carvalho Barbosa",
    categoria: "Sub-12-Masc",
    posicao: 0,
    pontos: 0,
  },
];

const resultadoSub18MascEtapa01New = [
  {
    atleta: "Lucas Figueiredo",
    categoria: "Sub-18-Masc",
    posicao: 1,
    pontos: 1000,
  },
  {
    atleta: "Matheus Figueiredo",
    categoria: "Sub-18-Masc",
    posicao: 0,
    pontos: 0,
  },
  {
    atleta: "Joao Gabriel Carvalho",
    categoria: "Sub-18-Masc",
    posicao: 4,
    pontos: 670,
  },
  {
    atleta: "Leonardo Da Silva",
    categoria: "Sub-18-Masc",
    posicao: 3,
    pontos: 730,
  },
  { atleta: "Luiz Breno", categoria: "Sub-18-Masc", posicao: 9, pontos: 500 },
  {
    atleta: "Guilherme Almeida",
    categoria: "Sub-18-Masc",
    posicao: 0,
    pontos: 0,
  },
  {
    atleta: "Guilherme Araujo",
    categoria: "Sub-18-Masc",
    posicao: 0,
    pontos: 0,
  },
  {
    atleta: "Alisson Silva",
    categoria: "Sub-18-Masc",
    posicao: 7,
    pontos: 555,
  },
  { atleta: "Miguel Botelho", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Abel Ribeiro", categoria: "Sub-18-Masc", posicao: 9, pontos: 500 },
  { atleta: "Noah Ribeiro", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Alberto Jasmin",
    categoria: "Sub-18-Masc",
    posicao: 2,
    pontos: 860,
  },
  { atleta: "Luan Azeredo", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Arthur Carvalho",
    categoria: "Sub-18-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Lucas Avellar", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Daniel Silva", categoria: "Sub-18-Masc", posicao: 5, pontos: 610 },
  {
    atleta: "Adenilson Santos",
    categoria: "Sub-18-Masc",
    posicao: 5,
    pontos: 610,
  },
  { atleta: "Davi Araujo", categoria: "Sub-18-Masc", posicao: 7, pontos: 555 },
  { atleta: "Caio Henrique", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Atila Ferreira", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Thiago Ladeira", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Ratinho Jhon Jhon",
    categoria: "Sub-18-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Luiz Gustavo", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Joao Nunes", categoria: "Sub-18-Masc", posicao: 9, pontos: 500 },
  {
    atleta: "Joao Gabriel Rodrigues",
    categoria: "Sub-18-Masc",
    posicao: 9,
    pontos: 500,
  },
  { atleta: "Rafael Lorenzo", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Matheus Machado Santos",
    categoria: "Sub-18-Masc",
    posicao: 13,
    pontos: 450,
  },
  { atleta: "Luiz Guilherme", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Kauan Pereira", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Davi Luze", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Arthur Steel", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
];

const resultadoSub18MascEtapa02New = [
  {
    atleta: "Lucas Figueiredo",
    categoria: "Sub-18-Masc",
    posicao: 7,
    pontos: 555,
  },
  {
    atleta: "Matheus Figueiredo",
    categoria: "Sub-18-Masc",
    posicao: 1,
    pontos: 1000,
  },
  {
    atleta: "Joao Gabriel Carvalho",
    categoria: "Sub-18-Masc",
    posicao: 5,
    pontos: 610,
  },
  {
    atleta: "Leonardo Da Silva",
    categoria: "Sub-18-Masc",
    posicao: 2,
    pontos: 860,
  },
  { atleta: "Luiz Breno", categoria: "Sub-18-Masc", posicao: 5, pontos: 610 },
  {
    atleta: "Guilherme Almeida",
    categoria: "Sub-18-Masc",
    posicao: 7,
    pontos: 555,
  },
  {
    atleta: "Guilherme Araujo",
    categoria: "Sub-18-Masc",
    posicao: 3,
    pontos: 730,
  },
  {
    atleta: "Alisson Silva",
    categoria: "Sub-18-Masc",
    posicao: 9,
    pontos: 500,
  },
  {
    atleta: "Miguel Botelho",
    categoria: "Sub-18-Masc",
    posicao: 9,
    pontos: 500,
  },
  { atleta: "Abel Ribeiro", categoria: "Sub-18-Masc", posicao: 9, pontos: 500 },
  { atleta: "Noah Ribeiro", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Alberto Jasmin", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Luan Azeredo", categoria: "Sub-18-Masc", posicao: 4, pontos: 670 },
  {
    atleta: "Arthur Carvalho",
    categoria: "Sub-18-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Lucas Avellar", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Daniel Silva", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Adenilson Santos",
    categoria: "Sub-18-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Davi Araujo", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Caio Henrique", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Atila Ferreira", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Thiago Ladeira",
    categoria: "Sub-18-Masc",
    posicao: 9,
    pontos: 500,
  },
  {
    atleta: "Ratinho Jhon Jhon",
    categoria: "Sub-18-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Luiz Gustavo", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Joao Nunes", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Joao Gabriel Rodrigues",
    categoria: "Sub-18-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Rafael Lorenzo", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Matheus Machado Santos",
    categoria: "Sub-18-Masc",
    posicao: 0,
    pontos: 0,
  },
  {
    atleta: "Luiz Guilherme",
    categoria: "Sub-18-Masc",
    posicao: 13,
    pontos: 450,
  },
  {
    atleta: "Kauan Pereira",
    categoria: "Sub-18-Masc",
    posicao: 13,
    pontos: 450,
  },
  { atleta: "Davi Luze", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Arthur Steel",
    categoria: "Sub-18-Masc",
    posicao: 13,
    pontos: 450,
  },
];

const resultadoSub18MascEtapa03New = [
  {
    atleta: "Lucas Figueiredo",
    categoria: "Sub-18-Masc",
    posicao: 9,
    pontos: 500,
  },
  {
    atleta: "Matheus Figueiredo",
    categoria: "Sub-18-Masc",
    posicao: 1,
    pontos: 1000,
  },
  {
    atleta: "Joao Gabriel Carvalho",
    categoria: "Sub-18-Masc",
    posicao: 5,
    pontos: 610,
  },
  {
    atleta: "Leonardo Da Silva",
    categoria: "Sub-18-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Luiz Breno", categoria: "Sub-18-Masc", posicao: 13, pontos: 450 },
  {
    atleta: "Guilherme Almeida",
    categoria: "Sub-18-Masc",
    posicao: 3,
    pontos: 730,
  },
  {
    atleta: "Guilherme Araujo",
    categoria: "Sub-18-Masc",
    posicao: 13,
    pontos: 450,
  },
  { atleta: "Alisson Silva", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Miguel Botelho",
    categoria: "Sub-18-Masc",
    posicao: 9,
    pontos: 500,
  },
  { atleta: "Abel Ribeiro", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Noah Ribeiro", categoria: "Sub-18-Masc", posicao: 2, pontos: 860 },
  { atleta: "Alberto Jasmin", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Luan Azeredo", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Arthur Carvalho",
    categoria: "Sub-18-Masc",
    posicao: 4,
    pontos: 670,
  },
  {
    atleta: "Lucas Avellar",
    categoria: "Sub-18-Masc",
    posicao: 5,
    pontos: 610,
  },
  { atleta: "Daniel Silva", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Adenilson Santos",
    categoria: "Sub-18-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Davi Araujo", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Caio Henrique",
    categoria: "Sub-18-Masc",
    posicao: 7,
    pontos: 555,
  },
  {
    atleta: "Atila Ferreira",
    categoria: "Sub-18-Masc",
    posicao: 7,
    pontos: 555,
  },
  { atleta: "Thiago Ladeira", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Ratinho Jhon Jhon",
    categoria: "Sub-18-Masc",
    posicao: 9,
    pontos: 500,
  },
  { atleta: "Luiz Gustavo", categoria: "Sub-18-Masc", posicao: 9, pontos: 500 },
  { atleta: "Joao Nunes", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  {
    atleta: "Joao Gabriel Rodrigues",
    categoria: "Sub-18-Masc",
    posicao: 0,
    pontos: 0,
  },
  {
    atleta: "Rafael Lorenzo",
    categoria: "Sub-18-Masc",
    posicao: 13,
    pontos: 450,
  },
  {
    atleta: "Matheus Machado Santos",
    categoria: "Sub-18-Masc",
    posicao: 0,
    pontos: 0,
  },
  { atleta: "Luiz Guilherme", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Kauan Pereira", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
  { atleta: "Davi Luze", categoria: "Sub-18-Masc", posicao: 13, pontos: 450 },
  { atleta: "Arthur Steel", categoria: "Sub-18-Masc", posicao: 0, pontos: 0 },
];

const resultadoSub18FemEtapa01New = [
  {
    atleta: "Mayara Goncalves",
    categoria: "Sub-18-Fem",
    posicao: 1,
    pontos: 1000,
  },
  { atleta: "Melissa Souza", categoria: "Sub-18-Fem", posicao: 2, pontos: 860 },
  { atleta: "Bia Martins", categoria: "Sub-18-Fem", posicao: 3, pontos: 730 },
  {
    atleta: "Manoela Giacomassi",
    categoria: "Sub-18-Fem",
    posicao: 4,
    pontos: 670,
  },
  {
    atleta: "Yasmin Martins",
    categoria: "Sub-18-Fem",
    posicao: 5,
    pontos: 610,
  },
  { atleta: "Isa Vidal", categoria: "Sub-18-Fem", posicao: 5, pontos: 610 },
];

const resultadoSub12FemEtapa01New = [
  {
    atleta: "Sophia Vargas",
    categoria: "Sub-12-Fem",
    posicao: 1,
    pontos: 1000,
  },
  {
    atleta: "Larissa Brandao",
    categoria: "Sub-12-Fem",
    posicao: 2,
    pontos: 860,
  },
  { atleta: "Alyne Moreira", categoria: "Sub-12-Fem", posicao: 3, pontos: 730 },
  {
    atleta: "Gabriela Oliveira",
    categoria: "Sub-12-Fem",
    posicao: 4,
    pontos: 670,
  },
  { atleta: "Ana Laura", categoria: "Sub-12-Fem", posicao: 5, pontos: 610 },
  { atleta: "Alice Fonseca", categoria: "Sub-12-Fem", posicao: 5, pontos: 610 },
  {
    atleta: "Isabela Oliveira",
    categoria: "Sub-12-Fem",
    posicao: 7,
    pontos: 555,
  },
];

const idEventoSaquarema = "974e8b9e-41cf-409f-838d-feef0a59b456";
const idEtapa01Brava = "0585de00-da36-46dc-8d34-7a423aefa0e6";
const idEtapa02RioDasOstras = "fccc1cc6-5128-42ca-aefc-2b2ed4f749a7";
const idEtapa03Pipeseca = "50f5f51f-97ab-402c-9e3f-1a55d5b0695a";
const idEtapa04CaboFrio = "b3b34286-824c-46f8-9723-b9bc9f691848";

const nameEventoSaquarema = "Festival de Verão Saquarema Bodyboard Kids 2025";
const nameEtapa01Brava = "Bravanesia Bodyboard 2025";
const nameEtapa02RioDasOstras = "Rio das Ostras Bodyboard Pro 2025";
const nameEtapa03Pipeseca = "Pipeseca Bodyboard Pro 2025";
const nameEtapa04CaboFrio = "Cabo Frio Contest 2025";

async function getAllAtletas() {
  try {
    const allAtletas = await db.select().from(atletas).all();
    return allAtletas;
  } catch (error) {
    console.error("Failed to retrieve atletas:", error);
    return [];
  }
}

async function insertResults(
  eventsToProcess: {
    eventId: string;
    eventName: string;
    results: {
      atleta: string;
      categoria: string;
      posicao: number;
      pontos: number;
    }[];
  }[],
) {
  try {
    const allAtletas = await getAllAtletas();
    const atletaMap = new Map(
      allAtletas.map((atleta) => [atleta.nome, atleta.id]),
    );

    const processResults = async (
      results: {
        atleta: string;
        categoria: string;
        posicao: number;
        pontos: number;
      }[],
      eventId: string,
      eventName: string,
    ) => {
      const formattedResultsPromises = results.map(async (result) => {
        let atletaId = atletaMap.get(result.atleta);
        if (!atletaId) {
          const [newAtleta] = await db
            .insert(atletas)
            .values({
              id: randomUUID(),
              nome: result.atleta,
            })
            .returning();
          atletaId = newAtleta.id;
          atletaMap.set(newAtleta.nome, newAtleta.id); // Update map for subsequent results in the same run
        }

        return {
          categoria: result.categoria,
          atletaId,
          atleta: result.atleta,
          posicao: result.posicao,
          pontos: result.pontos,
        };
      });

      const formattedResults = await Promise.all(formattedResultsPromises);

      const currentEvent = await db
        .select()
        .from(eventos)
        .where(eq(eventos.id, eventId))
        .all();

      if (currentEvent.length === 0) {
        console.error(
          "Event with ID",
          eventId,
          "not found. Please insert the event first.",
        );
        return;
      }

      const newEvent = await db
        .update(eventos)
        .set({
          resultados: [
            ...(currentEvent[0].resultados || []),
            ...formattedResults,
          ],
        })
        .where(eq(eventos.id, eventId))
        .returning();

      const groupedResults = newEvent[0].resultados
        ? newEvent[0].resultados.reduce(
            (acc, res) => {
              if (!acc[res.categoria]) {
                acc[res.categoria] = 0;
              }
              acc[res.categoria]++;
              return acc;
            },
            {} as Record<string, number>,
          )
        : {};
      console.log(
        `Evento ${eventName} atualizado com sucesso:`,
        groupedResults,
      );
    };

    for (const event of eventsToProcess) {
      await processResults(event.results, event.eventId, event.eventName);
    }
  } catch (error) {
    console.error(
      "Erro ao atualizar o evento para Sub-15-Masc Etapa 03:",
      error,
    );
  }
}

const eventUnamar: Event = {
  id: randomUUID(),
  nome: "Unamar Bodyboard Pro 2025",
  data: new Date("2025-10-25").toISOString(),
  local: "Cabo Frio",
  cartazUrl: "",
  fotos: [""],
  videos: [""],
  resultados: [
    {
      categoria: "",
      atleta: "",
      atletaId: "",
      posicao: 0,
      pontos: 0,
    },
  ],
};

const eventMacae: Event = {
  id: randomUUID(),
  nome: "Macaé Bodyboard Pro 2025",
  data: new Date("2025-11-14").toISOString(),
  local: "Macaé",
  cartazUrl: "",
  fotos: [""],
  videos: [""],
  resultados: [
    {
      categoria: "",
      atleta: "",
      atletaId: "",
      posicao: 0,
      pontos: 0,
    },
  ],
};

const eventBuzios: Event = {
  id: randomUUID(),
  nome: "Búzios Bodyboard Pro 2025",
  data: new Date("2025-12-05").toISOString(),
  local: "Búzios",
  cartazUrl: "",
  fotos: [""],
  videos: [""],
  resultados: [
    {
      categoria: "",
      atleta: "",
      atletaId: "",
      posicao: 0,
      pontos: 0,
    },
  ],
};

async function createEvent(event: Event) {
  const newEvent = await db.insert(eventos).values(event).returning();

  console.log("Event created", JSON.stringify(newEvent, null, 4));
}

createEvent(eventUnamar)
createEvent(eventMacae)
createEvent(eventBuzios)

insertResults([
  // { eventId: idEtapa01Brava, eventName: nameEtapa01Brava, results: resultadoSub15MascEtapa01New },
  // { eventId: idEtapa02RioDasOstras, eventName: nameEtapa02RioDasOstras, results: resultadoSub15MascEtapa02New },
  // { eventId: idEtapa03Pipeseca, eventName: nameEtapa03Pipeseca, results: resultadoSub15MascEtapa03New },
  //   { eventId: idEtapa04CaboFrio, eventName: nameEtapa04CaboFrio, results: resultadoProMascEtapa04New },
  // { eventId: idEtapa01Brava, eventName: nameEtapa01Brava, results: resultadoProFemEtapa01New },
  // { eventId: idEtapa02RioDasOstras, eventName: nameEtapa02RioDasOstras, results: resultadoProFemEtapa02New },
  // { eventId: idEtapa03Pipeseca, eventName: nameEtapa03Pipeseca, results: resultadoProFemEtapa03New },
  // { eventId: idEtapa04CaboFrio, eventName: nameEtapa04CaboFrio, results: resultadoProFemEtapa04New },
  // { eventId: idEtapa01Brava, eventName: nameEtapa01Brava, results: resultadoMasterEtapa01New },
  // { eventId: idEtapa02RioDasOstras, eventName: nameEtapa02RioDasOstras, results: resultadoMasterEtapa02New },
  // { eventId: idEtapa03Pipeseca, eventName: nameEtapa03Pipeseca, results: resultadoMasterEtapa03New },
  // { eventId: idEtapa04CaboFrio, eventName: nameEtapa04CaboFrio, results: resultadoMasterEtapa04New },
  // { eventId: idEtapa01Brava, eventName: nameEtapa01Brava, results: resultadoLegendEtapa01New },
  // { eventId: idEtapa02RioDasOstras, eventName: nameEtapa02RioDasOstras, results: resultadoLegendEtapa02New },
  // { eventId: idEtapa03Pipeseca, eventName: nameEtapa03Pipeseca, results: resultadoLegendEtapa03New },
  // { eventId: idEtapa04CaboFrio, eventName: nameEtapa04CaboFrio, results: resultadoLegendEtapa04New },
  // {
  //   eventId: idEventoSaquarema,
  //   eventName: nameEventoSaquarema,
  //   results: resultadoSub12FemEtapa01New,
  // },
  // { eventId: idEtapa02RioDasOstras, eventName: nameEtapa02RioDasOstras, results: resultadoSub18MascEtapa02New },
  // { eventId: idEtapa04CaboFrio, eventName: nameEtapa04CaboFrio, results: resultadoSub18MascEtapa03New },
]);
